### ISSUE TITLE
Community - Coming soon page

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#100]
When clicking on the Community icon in the bottom bar, the user should see this page 

<img width="438" alt="Screenshot 2023-10-03 at 11 48 23" src="https://github.com/TowneSquare/mobile/assets/139227890/048f10e2-0f6c-4bb1-b22d-647d37628528">

link to design: https://www.figma.com/file/sPKuOqonmL3eIDbWcOduIJ/Mobile-app?type=design&node-id=3839%3A23209&mode=design&t=WhyI3mz437121fBh-1

here you can download: [Community_ComingSoon.zip](https://github.com/TowneSquare/mobile/files/12791173/Community_ComingSoon.zip)

• animation.svg: svg animation of the lines
• example.webm: video of how do page should look like

**Comment by ddamazz** [comment]
@Pcharlesme 
<img width="376" alt="Screenshot 2023-10-03 at 11 52 47" src="https://github.com/TowneSquare/mobile/assets/139227890/025aded0-0cc3-4eaf-9fc7-0b621d968f7c">
If you think it would be better to export these images as webp instead of svg, let me know

**Comment by markots** [comment]
Done
