### ISSUE TITLE
[SIGNUP] Connecting using X is not working

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#125]
https://github.com/TowneSquare/mobile/assets/139227890/54e48adf-0de8-4e73-885f-32e02e539c5b

As you can see in the video, when I try to connect using X, I can't because it opens auth.magic.link and shows an error. When I connect using Discord, the connections goes wll, but the signup flow automatically continues (and I haven't tapped on "Continue" button). After continuing, I see again Signup with email (which is another error)

The correct flow for the user that wants to connect both socials should be:
1. User connects his X account
2. User connects his discord account
3. User taps on Continue

**Comment by codewizard870** [comment]
3. fixed in PR "fix/routing #124"

**Comment by markots** [comment]
done
