### ISSUE TITLE
[Signup flow] Referral code - Change 500 Ts points to 100 Cred points 

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#155]
https://www.figma.com/file/sPKuOqonmL3eIDbWcOduIJ/Mobile-app?type=design&node-id=4219%3A34800&mode=design&t=58GkGMj2xUG2ISKI-1

<img width="377" alt="Screenshot 2023-12-28 at 15 14 39" src="https://github.com/TowneSquare/mobile/assets/139227890/3a9fbb18-73a8-4fe9-b86f-61845bb1cf10">

Update text to: Enter the referral code and get 
100 Cred Points!

**Comment by markots** [comment]
done
