### ISSUE TITLE
[Community tab and Community page] Add animated background

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#156]
Here are the animated lines in animated svg. It should be aligned in the top left corner of the screen 
[Coming soon - Community section.svg.zip](https://github.com/TowneSquare/mobile/files/13787195/Coming.soon.-.Community.section.svg.zip)

Here is the background https://www.figma.com/file/sPKuOqonmL3eIDbWcOduIJ/Mobile-app?type=design&node-id=4150%3A12680&mode=design&t=8oipmIoPmf3LRgUU-1

**Comment by markots** [comment]
done
