### ISSUE TITLE
[Referral poster] Change 500 to 100, Change TS points to Cred points

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#158]
<img width="571" alt="Screenshot 2023-12-28 at 15 32 31" src="https://github.com/TowneSquare/mobile/assets/139227890/44250181-5d2d-4481-827b-40e66dbf176a">

The updated text should look like this 
https://www.figma.com/file/sPKuOqonmL3eIDbWcOduIJ/Mobile-app?type=design&node-id=4245%3A36753&mode=design&t=8oipmIoPmf3LRgUU-1

**Comment by markots** [comment]
done
