### ISSUE TITLE
[Rewards page] Remove "i" icon rom these pages

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#159]
<img width="316" alt="Screenshot 2023-12-28 at 15 37 32" src="https://github.com/TowneSquare/mobile/assets/139227890/d97ed63f-0244-4769-acef-9bad85a0372a">
<img width="323" alt="Screenshot 2023-12-28 at 15 39 47" src="https://github.com/TowneSquare/mobile/assets/139227890/92a0e440-f8d9-47a7-a707-c7ad32c01349">

Remove the white info "i" icon from these pages in the selected areas (red squares)
Also pls change the title from "TS points" to "Cred points"

**Comment by markots** [comment]
done
