### ISSUE TITLE
[Rewards] Rename title in the "NFT holdings - single collection" page 

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#165]
https://www.figma.com/file/sPKuOqonmL3eIDbWcOduIJ/Mobile-app?type=design&node-id=4222%3A35317&mode=design&t=8oipmIoPmf3LRgUU-1
<img width="418" alt="Screenshot 2023-12-28 at 17 29 51" src="https://github.com/TowneSquare/mobile/assets/139227890/7bf46585-4b19-46ea-9e20-9a1227fc5077">
Rename text in "Points from this collection"

**Comment by markots** [comment]
done
