### ISSUE TITLE
[Signup flow] Update username field

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#166]
![image](https://github.com/TowneSquare/mobile/assets/139227890/14e493f5-c177-4eb3-80fe-d9e9c813f0b8)
![image](https://github.com/TowneSquare/mobile/assets/139227890/8f0e9368-bbe2-4cee-8482-0835bdbfd76c)

The username field in the signup flow should behave in the same way as the username field in the Edit profile page, i.e. when you tap on it, the @ should remain visible

**Comment by markots** [comment]
done
