### ISSUE TITLE
[Rewads - Airdrop] Icons should be bigger

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#167]
![image](https://github.com/TowneSquare/mobile/assets/139227890/91c83e61-77c3-4221-8049-0a111ae7ac30)

figma link: https://www.figma.com/file/sPKuOqonmL3eIDbWcOduIJ/Mobile-app?type=design&node-id=4148%3A34271&mode=design&t=8oipmIoPmf3LRgUU-1

<img width="132" alt="Screenshot 2023-12-28 at 17 38 52" src="https://github.com/TowneSquare/mobile/assets/139227890/cc8cc97a-403f-4483-b69c-8d7798b00656">

Icon size should be 32px. Also check icon sizes in **Earnings tab**

**Comment by markots** [comment]
done
