### ISSUE TITLE
[Support] Buttons are not working

### ISSUE THREAD

**Issue by ddamazz** [TowneSquare/mobile#168]
<img width="298" alt="Screenshot 2023-12-28 at 18 02 47" src="https://github.com/TowneSquare/mobile/assets/139227890/a00f85ea-d616-4c11-9d17-151eace44d62">

Email should open support@townesquare.xyz in the phone's default browser
Discord: https://discord.gg/xnTQh7SsRZ
X: https://twitter.com/TowneSquarexyz

**Comment by markots** [comment]
done
