### ISSUE TITLE
[NOTIFICATIONS] Clicking on PFP in Notification doesn't open user profile

### ISSUE THREAD

**Issue by markots** [TowneSquare/mobile#238]
Currently, when clicking on the PFP or username in the notification element, it does not open the user profile as expected. 
<img width="414" alt="Screenshot 2024-04-23 alle 16 29 18" src="https://github.com/TowneSquare/mobile/assets/112094900/2e99dd5e-76e0-485f-a5a6-bd7c657658ed">

**Comment by Pcharlesme** [comment]
@markots What was the plan for this notification, it it for follow or what

**Comment by markots** [comment]
If the notification is from another user (i.e. User1 started following you) then User1 pfp and his username on the notification are clickable and will lead to User1 profile. Make sense? @Pcharlesme

**Comment by markots** [comment]
done
