### ISSUE TITLE
[Create single post] Fix the behaviour of "Remove the attached NFT in order to add images, videos, GIFs or other NFTs." snackbar

### ISSUE THREAD

**Issue by d2Dreamer** [TowneSquare/mobile#45]
The Snackbar component with the text "Remove the attached NFT in order to add images, videos, GIFs or other NFTs." should appear when a user click on camera/image/GIF7NFT icon after an NFT has been attached.

Its purpose is to explain why it's not possible to add additional images, gif or NFTs if 1 NFT is already attached to the post.

<img width="225" alt="big-Screenshot 2023-07-12 at 13 47 22" src="https://github.com/TowneSquare/mobile/assets/41088824/a57c36d7-4374-4463-8792-045ab91d29b5">
<img width="225" alt="big-Screenshot 2023-07-12 at 13 47 05" src="https://github.com/TowneSquare/mobile/assets/41088824/9b49321a-b834-4c36-91fe-2654c2861f8d">

**Comment by markots** [comment]
Done
